---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: 'latest'

inputs:
- name: project-src

run:
  path: sh
  args:
  - -exc
  - |
    whoami
    env
    go version
    find .
    touch some-output/my-built-artifact
