---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: centos/nodejs-6-centos7
    tag: 'latest'

inputs:
- name: project-src

run:
  path: sh
  args:
  - -exc
  - |
    whoami
    env
    cd project-src
    mkdir ../built-project/
    tar -cvzf ../built-project/release-1.0.0.tgz .
    ls -l ../built-project/
    cd ../built-project
    

outputs:
- name: built-project
