---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: centos/nodejs-6-centos7
    tag: 'latest'

inputs:
- name: project-src

run:
  path: sh
  args:
  - -exc
  - |
    whoami
    ls -l
    ls -ll built-project
    tar -zxvf prog-1-jan-2005.tar.gz
    tar -zxvf built-project/prog-1-jan-2005.tar.gz

    

outputs:
- name: built-project
