---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: centos/nodejs-6-centos7
    tag: 'latest'

inputs:
- name: project-src

run:
  path: sh
  args:
  - -exc
  - |
    whoami
    env
    cd project-src
    mkdir /tmp/finalversion/
    tar -cvzf /tmp/finalversion/release-1.0.0.tgz .
    ls -l /tmp/finalversion/
    

outputs:
- name: built-project
  path: /tmp/finalversion/
