---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: centos/nodejs-6-centos7
    tag: 'latest'

inputs:
- name: project-src

run:
  path: sh
  args:
  - -exc
  - |
    whoami
    ls -l
    tar -zcvf built-project/release.tar.gz project-src
    ls -l built-project/

    

outputs:
- name: built-project
