---
platform: linux
image_resource:
  type: docker-image
  privileged: true
  source:
    repository: centos/nodejs-6-centos7
    tag: 'latest'

inputs:
- name: project-src

run:
  path: sh
  args:
  - -exc
  - |
    whoami
    ls -l
    tar -cvzf /tmp/release-1.0.0.tgz built-project/
    mv /tmp/release-1.0.0.tgz built-project/release-1.0.0.tgz

    

outputs:
- name: built-project
