---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: 'latest'

inputs:
- name: project-src

run:
  path: sh
  args:
  - -exc
  - |
    whoami
    env
    cd project-src
    npm install
    mkdir built-project
    cp -r * /built-project/
    

outputs:
- name: built-project
