---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: centos/nodejs-6-centos7
    tag: 'latest'

inputs:
- name: project-src

run:
  path: sh
  args:
  - -exc
  - |
    whoami
    env
    cd project-src
    mkdir /built-project
    tar -cvzf /built-project/release.tgz .
    ls -l /built-project/
    

outputs:
- name: built-project
  path: /built-project
